version: '3.5'
services:
  timescaledb:
    container_name: tcc_timescaledb
    image: timescale/timescaledb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
  grafana:
    container_name: tcc_grafana
    image: grafana/grafana:6.3.5
    ports:
      - 6001:3000
    volumes:
      - grafanadata:/var/lib/grafana
    networks:
      - vm_net
    restart: always

volumes:
  pgdata: {}
  grafanadata: {}
networks:
  vm_net:
